Create event page for talk at Wellcome Genome Campus
nf-core/website pull request #1997
Opened 2023-09-26 13:06 UTC by priyanka-surana

- Can we add external talks about Nextflow to the events page?
- Have I entered the time correctly? It is 2pm to 3pm UK time.

2023-09-26 13:29 UTC, ewels commented
@nf-core-bot fix linting

2023-09-26 13:36 UTC, priyanka-surana commented
@nf-core-bot fix linting

2023-09-26 13:49 UTC, christopher-hakkaart requested changes

2023-09-26 13:49 UTC, christopher-hakkaart commented on src/content/events/2023/talk_nextflow_in_action.md
> +<br>Genomics England provides whole genome sequencing diagnostics to the Genomic Medicine Service (U.K), a free at the point-of-care, nationwide, genomic diagnostic testing service, with ambitious ta
```suggestion
## Luke Paul Buttigieg and Ricardo Humberto Ramirez Gonzalez, Genomics England

**Porting clinical genome analysis to Nextflow at Genomics England**

Genomics England provides whole genome sequencing diagnostics to the Genomic Medicine Service (U.K), a free at the point-of-care, nationwide, genomic diagnostic testing service, with ambitious targets of processing 300,000 samples by 2025. Currently, all clinical bioinformatics is processed using a clinical-standard certified, internally developed workflow engine (Bertha). We are migrating to a new solution (Genie) which combines Nextflow and Nextflow Tower with custom functionality, so we can focus on our core mission to enable equitably accessed, genomics medicine for all. Genie should help us support newer use cases quicker, across different infrastructures such as cloud, and uses a standard workflow definition language. We have developed an approach to migrate at speed in an agile and iterative fashion. We are mocking the services in the workflow environment in Docker containers to allow us to run continuous integration tests. We are using an automated comparison testing framework to compare the existing system with the new one to detect regressions. Later, we will iteratively refactor the workflows, breaking up the Singularity image and optimising for performance. In this talk, we will describe this migration strategy, risk management and lessons learnt while working through this large-scale effort.
```

2023-09-26 13:49 UTC, christopher-hakkaart commented on src/content/events/2023/talk_nextflow_in_action.md
> +<br>Tree of Life is the latest scientific programme of the Wellcome Sanger Institute, aiming at producing reference genome assemblies for tens of thousands of species. We decided early on that Nextfl
```suggestion
## Matthieu Muffato, Tree of Life, Wellcome Sanger Institute

**Adopting Nextflow in Sanger Tree of Life**

Tree of Life is the latest scientific programme of the Wellcome Sanger Institute, aiming at producing reference genome assemblies for tens of thousands of species. We decided early on that Nextflow would be the workflow manager of choice - what an adventure it has been ! In this presentation, I will tell you about our journey, starting from training users, setting up development environments, right up to advertising our complete pipelines and reaching out to users outside of the department, with some insights into deploying and automating the pipelines.
```

2023-10-04 11:09 UTC, priyanka-surana commented
Standard prettier does not work for me on this file. 
```
$ prettier -w src/content/events/2023/talk_nextflow_in_action.md
[error] Invalid configuration for file "/lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/website/src/content/events/2023/talk_nextflow_in_action.md":
[error] Cannot find module 'prettier-plugin-astro'
[error] Require stack:
[error] - /lustre/scratch123/tol/teams/tolit/users/ps22/pipelines/website/.prettierrc.cjs
[error] - /software/treeoflife/miniconda3/envs/nf-core_2.10/lib/node_modules/prettier/internal/internal.mjs
```
@christopher-hakkaart Let me know what needs doing to get this file merged. Thank you.

2023-10-04 13:30 UTC, mashehu commented
@nf-core-bot fix linting

2023-10-10 09:20 UTC, merged