Add blog
nf-core/website pull request #2072
Opened 2023-10-31 14:45 UTC by mashehu

2023-11-02 10:19 UTC, ewels commented
Some extra fields to show:

* Publish date
* Author(s) - GitHub handles
* Year sidebar

2023-11-03 13:22 UTC, FriederikeHanssen commented on src/content/blog/2023/hello-nf-core-world.mdx
> +-   Share substantive updates from our community’s activities.
```suggestion
-   Share substantive updates from our community’s activities, like pipeline releases
```

2023-11-03 14:02 UTC, FriederikeHanssen commented on src/content/blog/2023/hello-nf-core-world.mdx
> +-   Share substantive updates from our community’s activities.
or add examples elsewhere. For me it is not super clear from reading this, that it is for pipeline developers to show case their new releases :)

2023-11-09 14:31 UTC, ewels reviewed
Getting a 404 on blog post links

2023-11-09 14:31 UTC, ewels commented on src/pages/blog/index.astro
> +                                        <a href={post.slug} class="stretched-link" />
```suggestion
                                        <a href={'/blog/'+post.slug} class="stretched-link" />
```

2024-01-12 15:33 UTC, ewels requested changes
Nearly there.. I think we're close.

Few minor glitches:

Sidebar overlap with ToC:
![CleanShot 2024-01-12 at 16 27 48@2x](https://github.com/nf-core/website/assets/465550/de0f4b09-d044-44be-b47c-546f9c9db2f3)

Social card doesn't show subtitle:
![image](https://github.com/nf-core/website/assets/465550/9b55d669-1be0-4e6d-adbc-b71a7a9ed1bf)

Page layout has space for a sidebar, but nothing there - could be good to have the blog archive as a sidebar?
![CleanShot 2024-01-12 at 16 30 17@2x](https://github.com/nf-core/website/assets/465550/ecf3fc7e-0de5-45e4-8250-8b658d27f429)

Feature image is on the listing card, but not on the blog post itself or social card or anything else. Could we also feature it on the detail page, for continuity?
![CleanShot 2024-01-12 at 16 31 20@2x](https://github.com/nf-core/website/assets/465550/7c15c6fc-a24f-43fb-969d-16212e7994ff)

Alternatively to above, could ditch the image and instead have a more traditional "post preview" of each article, with a truncated snippet. Basically like the [Nextflow blog](https://nextflow.io/blog.html), but with the sidebar showing dates (and blog titles? - should be consistent with the sidebar on the detail page).

2024-01-12 15:33 UTC, ewels commented on src/content/blog/2023/hello-nf-core-world.mdx
> +pubDate: 2023-11-03T08:00:00.000+01:00
Need to move it into a `2024` directory..

```suggestion
pubDate: 2024-12-12T17:14:23.894+01:00
```

2024-01-12 15:33 UTC, ewels commented on src/content/blog/2023/hello-nf-core-world.mdx
> +Contributing to this blog is quite straight forward. You just need to add a markdown (or MDX) file to the `src/content/blog` folder.
```suggestion
Contributing to this blog is quite straight forward. You just need to add a markdown (or MDX) file to the `src/content/blog/<year>` folder.
```

2024-01-12 15:33 UTC, ewels commented on src/content/blog/2023/hello-nf-core-world.mdx
> +Similar to the events page, also our blog posts come with an RSS feed. Subscribe to it at [https://nf-co.re/blog/rss.xml](https://nf-co.re/blog/rss.xml) to stay up to date with the latest posts.
We should create a new slack channel for this to auto-post to as well, and mention it here.

2024-01-12 17:42 UTC, mashehu commented on src/pages/blog/[...blogpost].astro
> +);
```suggestion
```

2024-01-12 18:53 UTC, ewels approved these changes
Awesome!

Couple of very minor things, but then LGTM to merge 👍🏻 

Can we have a title / heading on the left hand sidebar? Also, could the index listing page show the blog post titles? (Already does this now on the single post detail page).

![CleanShot 2024-01-12 at 19 51 34@2x](https://github.com/nf-core/website/assets/465550/ce5002a4-b872-40ea-9c12-1c249cf80678)

2024-01-12 18:54 UTC, ewels commented on src/content/blog/2024/hello-nf-core-world.mdx
> +subtitle: 'The inital nf-core blog post'
```suggestion
subtitle: A new blog for nf-core is launched! Here's what to expect.
```

2024-01-12 18:58 UTC, ewels commented on src/pages/blog/index.astro
> +                                        <p class="card-text">
Do we want to put the subtitle under here?
```suggestion
                                        <h2 transition:name="title">{post.data.title}</h2>
                                        <p class="lead">{post.data.subtitle}</p>
                                        <p class="card-text small">
```

2024-01-12 21:57 UTC, ewels approved these changes
Let's do it!

2024-01-12 21:57 UTC, ewels commented on src/pages/blog/index.astro
> +                    slug: post.slug,
```suggestion
                    slug: '/blog/' + post.slug,
```

2024-01-12 21:57 UTC, merged