Add LinkedIn and Bluesky to the "Join" page
nf-core/website pull request #2378
Opened 2024-03-18 13:13 UTC by camlloyd

This PR addresses https://github.com/nf-core/website/issues/2373, adding LinkedIn and Bluesky buttons to the "Join" page.
Bluesky is not available on FA yet but is due to be included in the next release. See: https://github.com/FortAwesome/Font-Awesome/issues/19810

2024-03-18 13:35 UTC, maxulysse approved these changes
LGTM

2024-03-18 13:36 UTC, christopher-hakkaart approved these changes

2024-03-18 13:36 UTC, maxulysse requested changes
Super good, can you add some more details

2024-03-18 14:24 UTC, ewels commented on src/pages/join.astro
> +            Bluesky
Would be great to use the Bluesky logo, it's available on Iconify here: https://icon-sets.iconify.design/simple-icons/bluesky/

So should be able to use it with the `<Icon>` element, if added to `astro.config.mjs` as well.

2024-03-19 09:22 UTC, mashehu requested changes

2024-03-19 09:22 UTC, mashehu commented on package.json
> +        "astro-iconify": "^1.2.0",
do we really need `astro-iconify` if we already have `astro-icon`

2024-03-19 10:32 UTC, mashehu commented on src/pages/join.astro
> +        depth: 1,
add icon here to show it in the toc

2024-03-25 08:19 UTC, mashehu approved these changes

2024-03-25 08:35 UTC, ewels commented
I see some weird icons in the ToC on the deployment preview:

![CleanShot 2024-03-25 at 09 33 39@2x](https://github.com/nf-core/website/assets/465550/2b5e8052-3dee-4a33-b881-d165a1fb8d5b)

Otherwise looking good 👍🏻

2024-03-25 08:38 UTC, mashehu commented
Fixed now

2024-03-25 08:42 UTC, mashehu commented
@camlloyd hit merge, whenever you are happy 🙂

2024-03-25 10:09 UTC, ewels commented
![CleanShot 2024-03-25 at 11 09 06@2x](https://github.com/nf-core/website/assets/465550/12442044-c91a-477e-ae7d-a4396c1a7258)

2024-03-25 10:25 UTC, camlloyd commented
OK to squash?

2024-03-25 11:12 UTC, merged