Future AnimalGenomics talks
nf-core/website pull request #2497
Opened 2024-05-06 15:11 UTC by bjlang

2024-05-06 21:05 UTC, JoseEspinosa requested changes

2024-05-06 21:05 UTC, JoseEspinosa commented on src/content/events/2024/SIG_animalgenomics_June
> +title: '#animal-genomics: Inaugural Meeting'
```suggestion
title: '#animal-genomics: TBC'
```

2024-05-06 21:05 UTC, JoseEspinosa commented on src/content/events/2024/SIG_animalgenomics_May
> +title: '#animal-genomics: Inaugural Meeting'
```suggestion
title: '#animal-genomics: TBC'
```

2024-05-06 21:05 UTC, JoseEspinosa commented on src/content/special-interest-groups/animal-genomics/meetings.md
>  The first meeting will be on Wednesday, April 17th, at 16:00 CEST. For this inaugural session, we are honored to announce Christa Kühn, president of the Friedrich Loeffler Institute, BovReg project c
Maybe we should update this then to be a general introductory text for all the meetings?

2024-05-06 21:05 UTC, JoseEspinosa commented on src/content/special-interest-groups/animal-genomics/meetings.md
> +| Apr 17 | Christa Kühn (BovReg; Friedrich Loeffler Institute, Germany) |
Could we add the link to the respective event here?

2024-05-08 15:38 UTC, bjlang commented
@nf-core-bot fix linting

2024-05-09 12:59 UTC, bjlang commented
@nf-core-bot fix linting

2024-05-09 15:52 UTC, JoseEspinosa approved these changes
Awesome job! 🚀

2024-05-09 16:01 UTC, merged