Add checklist to update maintainers team
nf-core/website pull request #2584
Opened 2024-06-17 20:37 UTC by edmundmiller

- **chore: Add Slack Message from @jfy133**
- **Try to use fancy checklists**

2024-06-18 09:03 UTC, jfy133 commented
@edmundmiller I don't seem to be able to find the page (either by clicking through the website or guessing the URL), any ideas?

2024-06-18 09:04 UTC, jfy133 commented
Oh, wait found it!

2024-06-18 09:07 UTC, jfy133 approved these changes
LGTM but I sort of wonder if it makes sense to have this page exposed in the docs overview page... It's only basically for 3 people +maybe the maintainers team in an an emergency (technically)

2024-06-18 09:07 UTC, jfy133 commented on src/content/docs/checklists/maintainers_team_updates.mdx
> +
```suggestion
Roughly once a year we review the maintainers team to ensure we have sufficient capacity to keep up with the community activity. 

The following steps are what the maintainers team leads need to do during the review. 

```

2024-06-18 09:07 UTC, jfy133 commented on src/content/docs/checklists/maintainers_team_updates.mdx
> +5. [ ] Once accepted, make PRs and merge in:
```suggestion
5. [ ] Once accepted, make PRs to add/move to alumni members and merge in:
```

2024-06-18 09:24 UTC, mashehu commented
> LGTM but I sort of wonder if it makes sense to have this page exposed in the docs overview page... It's only basically for 3 people +maybe the maintainers team in an an emergency (technically)

Yeah, had the same feeling...

2024-06-18 12:05 UTC, jfy133 commented
Can we leave the file in the same place but not index it in the docs overview section @mashehu ? Like 'hidden: true' in the header or something?

2024-06-18 12:52 UTC, mashehu commented
We don't have that option, not sure if we really want to have hidden files...

2024-06-18 13:18 UTC, jfy133 commented
Hidden only from being displayed in the overview, not that the page isn't accessible at all (if you see what I mean).

2024-06-18 13:34 UTC, edmundmiller commented
> Hidden only from being displayed in the overview, not that the page isn't accessible at all (in case I wasn't clear)

Yeah, I agree with this. I don't think there's anything sensitive in there, but it would just be clutter that most people won't ever need.

2024-11-04 10:24 UTC, jfy133 commented
Whelp forgot about this, what about  a section under 'Guidelines' called 'Governance', allows transprency but not something someone would normally click on

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +This documents the steps that need to be performed when a new pipeline is accepted via #new-pipelines
```suggestion
This document outlines the steps to be performed when a new pipeline is accepted via #new-pipelines channel
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +1. [ ] Core: Check proposal has received approval on #new-pipelines from either:
```suggestion
1. [ ] Core: Check proposal has received approval in #new-pipelines from either:
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - at least 2 members of core team
```suggestion
    - at least two members of the core team
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - at least 1 member of core team and 1 member of maintainers team
```suggestion
    - at least one member of the core team and one member of the maintainers team.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +2. [ ] Core: Check name follows [pipeline naming guidelines](/docs/guidelines/pipelines/workflow_name)
```suggestion
2. [ ] Core: Verify that the pipeline name follows the [pipeline naming guidelines](/docs/guidelines/pipelines/workflow_name).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +3. [ ] Core: Make slack channel with approved name
```suggestion
3. [ ] Core: Create a slack channel with approved pipeline name.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +4. [ ] Core: Ask developer to join #pipeline-maintainers
```suggestion
4. [ ] Core: Ask the developers to join #pipeline-maintainers channel.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +5. [ ] Core/Dev: Make git repository with nf-core create and push to GitHub
```suggestion
5. [ ] Core/Dev: Create the git repository using `nf-core create` and push it to GitHub.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +6. [ ] Core/Dev: Transfer repository to nf-core GitHub organisation and delete repository on local machine
```suggestion
6. [ ] Core/Dev: Transfer the repository to nf-core GitHub organisation and delete the repository on local machine.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +7. [ ] Core/Dev: Sync the nf-co.re pipelines page by manually triggering the GitHub action (website repo > actions > build json files and md-cache > Run workflow > from main)
```suggestion
7. [ ] Core/Dev: Sync the nf-co.re pipelines page by manually triggering the GitHub action (website repo -> actions -> build json files and md-cache -> Run workflow -> from main).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +Uploading full-test AWS files for a pipeline to S3 bucket information:
```suggestion
Instructions for uploading full-test AWS files for a pipeline to a S3 bucket:
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - [ ] Small input data that maybe flaky when downloaded from other repositories
```suggestion
    - [ ] Small input data that maybe unreliable when downloaded from other repositories
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +            e.g. Max of 10GB for the total across all files
```suggestion
            (e.g., limit total file size to a maximum of 10GB across all files)
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - [ ] Very large files that cannot be reduced or subset
```suggestion
    - [ ] Very large files that cannot be reduced or subsetted.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +-   [ ] When creating the pipeline directory in the bucket, use the 'Amazon S3-managed keys (SSE-S3) option
```suggestion
-   [ ] When creating the pipeline directory in the S3 bucket, select the 'Amazon S3-managed keys (SSE-S3)` option.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +Anyone who is in the nf-core organization can do this!
```suggestion
Instructions for setting up Zenodo DOIs. Anyone in the nf-core organization can do this!
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +1. [ ] Sign up with Zenodo and log in
```suggestion
1. [ ] Sign up on Zenodo and log in.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +2. [ ] Make sure you have connected your github (Settings -> GitHub -> Connect Account)
```suggestion
2. [ ] Connect your Github account (Go to Settings -> GitHub -> Connect Account).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +4. [ ] Flip switch against all nf-core _pipeline_ repositories in the list of repositories to 'On' (including the one that you want to assign)
```suggestion
4. [ ] Enable Zenodo archiving for all nf-core pipeline repositories by toggling the switch to `On` (including the one you want to assign).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - Might as well do this for all (active) pipelines you see, as DOIs won't be assigned until release anyway
```suggestion
    - It’s a good idea to enable this for all active pipelines, as DOIs will only be assigned upon release.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - Some will not activate (e.g. nf-core/exoseq) as they are archived!
```suggestion
    - Note: Some repositories (e.g. nf-core/exoseq) may not activate if they are archived.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +5. [ ] Tell pipeline developer to make a release
```suggestion
5. [ ] Inform the pipeline developers to make a release.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +1. [ ] Go to Zenodo and find the repository of interest on the list repositories under Settings -> Github
```suggestion
1. [ ] Go to Zenodo and find the relevant repository in Settings -> Github.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +2. [ ] Click through to the release's Zenodo 'record' page
```suggestion
2. [ ] Click through to the Zenodo 'record' page for the release.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +3. [ ] Scroll down and look on the right-hand side of the page for the 'Communities' box, submit the record to the nf-core community
```suggestion
3. [ ] On the record page, scroll down and look on the right-hand side and find the `Communities` box. Submit the record to the nf-core community.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +5. [ ] Copy the 'cite all versions by using the DOI ' DOI (_not_ the specific release!)
```suggestion
4. [ ] Scroll down and again on the right-hand side of the page for the `Versions` box, copy the DOI for 'cite all versions by using the DOI ' (_not_ the specific release DOI).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +6. [ ] On the master branch of the pipeline's repository, edit the following files:
```suggestion
5. [ ] Update the following files on the master branch of the pipeline repository:
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - **README.md**: Zenodo Badge at the top, and 'If you use this pipeline cite:' at the bottom (make sure to uncomment this section too)
```suggestion
    - **README.md**: Add the Zenodo Badge at the top and update the 'If you use this pipeline cite:' section at the bottom (make sure to uncomment this section too).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - **Nextflow.config**: manifest's DOI entry
```suggestion
    - **Nextflow.config**: Update the manifest block to include the DOI.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - Commit with something like 'Add Zenodo ID after first release'
```suggestion
    - Commit these changes with a message like 'Add Zenodo ID after first release'.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +Anyone can request to join the nf-core GitHub organisation via #github-invitations.
```suggestion
Anyone can request to join the nf-core GitHub organisation via #github-invitations channel.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +1.  [ ] Check they have a reasonable to join (clearly not spam)
```suggestion
1.  [ ] Verify the request is reasonable (i.e., clearly not spam).
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +2.  [ ] Invite via https://github.com/orgs/nf-core/teams
```suggestion
2.  [ ] Send an invitation via [nf-core github teams](https://github.com/orgs/nf-core/teams)
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +3.  [ ] Make sure to do team 'contributors' https://github.com/orgs/nf-core/teams/contributors
```suggestion
3.  [ ] Add them to the [nf-core contributors team](https://github.com/orgs/nf-core/teams/contributors)
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +4.  [ ] Press ✅ on their message in #github-invitations
```suggestion
4.  [ ] Confirm by reacting with ✅ on their message in #github-invitations channel.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +We need to update the [bingo cards](https://nfcore-bingo.web.app/) before each hackathon to ensure they remain up-to-date.
```suggestion
Before each hackathon, we need to update the [bingo cards](https://nfcore-bingo.web.app/) to ensure they remain current.
```

2024-11-09 11:59 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +1. [ ] Get the outreach google account credentials
```suggestion
1. [ ] Get the outreach google account credentials from `@core-team`
```

2024-11-09 13:12 UTC, jfy133 commented
@nf-core-bot fix linting

2024-11-09 13:35 UTC, sateeshperi commented on src/content/docs/checklists/community_governance/core_team.mdx
> +5. [ ] Core/Dev: Create the git repository using `nf-core create` and push it to GitHub.
```suggestion
5. [ ] Core/Dev: Create the git repository using `nf-core pipelines create` and push it to GitHub.
```

2024-11-09 13:36 UTC, sateeshperi approved these changes

2024-11-11 08:29 UTC, christopher-hakkaart requested changes
It looks pretty good to me. A few minor comments to remove excess words.

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +4. [ ] Add new maintainers to the [Maintainers team google calendar](https://calendar.google.com/calendar/u/0?cid=ZDA3MmVkOGI1NzQ0YWViOWE3ZjBkMDE4YjFjZWE1OGE5M2MwZDZlZTIyMzM1YWE5YzA0NTlmODg0YTZkMDNkZ
```suggestion
4. [ ] Add member to the [Maintainers team google calendar](https://calendar.google.com/calendar/u/0?cid=ZDA3MmVkOGI1NzQ0YWViOWE3ZjBkMDE4YjFjZWE1OGE5M2MwZDZlZTIyMzM1YWE5YzA0NTlmODg0YTZkMDNkZEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +Team Leads:
```suggestion
Team lead:
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +1. [ ] Make a PR to nf-core website adding themselves to the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```suggestion
1. [ ] Add self profile to the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +## Maintainers Team Yearly Maintenance
```suggestion
## Maintainers team membership
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +Maintainers can be added at any point of the year at the nomination of the community.
```suggestion
New maintainers may be nominated by the community and join the team at any time.
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +Yearly maintenance is performed to ensure everything is up-to-date particularly in regards to members who step down.
```suggestion
Maintainers maintenance is performed yearly to ensure membership is up-to-date, particularly in regards to members who wish to step down due to new or changing commitments.
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +2. [ ] Ask for nominations in maintainers meeting, discuss and approve
```suggestion
2. [ ] Ask for nominations, discuss, and approve new members
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +5. [ ] Move members who are stepping down to alumni status on website in the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```suggestion
5. [ ] Move members who step down to alumni status on the website in the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +6. [ ] Announce on [#announcements](https://nfcore.slack.com/archives/CE6P95170)
```suggestion
6. [ ] Announce new members on [#announcements](https://nfcore.slack.com/archives/CE6P95170)
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/core_team.mdx
> +This document outlines the steps to be performed when a new pipeline is accepted via the #new-pipelines channel
```suggestion
Instructions for nf-core pipeline approval:
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +## Maintainers Team Onboarding
```suggestion
## Maintainers team onboarding
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/core_team.mdx
> +It's recommended that a core team member does these steps as it makes it easier for us to transfer to the nf-core Zenodo community.
```suggestion

:::note
It's recommended that a core team member transfers the DOI to the nf-core Zenodo community.
:::
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/core_team.mdx
> +    - Note: Some repositories (e.g. nf-core/exoseq) may not activate as they are archived.
```suggestion
    - Note: Some repositories (e.g., nf-core/exoseq) may not activate as they are archived.
```

2024-11-11 08:29 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/core_team.mdx
> +4. [ ] In the middle click “games” and navigate down the tree until you reach “lexicon”
```suggestion
4. [ ] Click “games” and navigate down the tree until you reach “lexicon”
```

2024-11-14 08:22 UTC, christopher-hakkaart requested changes
I'd like to trend towards some consistent stylistic changes. Content is the same. Please check formatting of the notes I added.

2024-11-14 08:22 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +6. [ ] Announce new members on [#announcements](https://nfcore.slack.com/archives/CE6P95170)
```suggestion
1. [ ] Ask who wants to step down.
2. [ ] Ask for nominations, discuss, and approve new members.
3. [ ] Invite nominees to join.
4. [ ] Once accepted, nominee and team leads perform tasks [onboarding](#maintainers-team-onboarding).
5. [ ] Move members who step down to alumni status on the website in the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers).

6. [ ] Announce new members on [#announcements](https://nfcore.slack.com/archives/CE6P95170).
```

2024-11-14 08:22 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +1. [ ] Add self profile to the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```suggestion
1. [ ] Add profile [**About > Governance > Maintainers**](https://nf-co.re/governance#maintainers)
```

2024-11-14 08:22 UTC, christopher-hakkaart commented on src/content/docs/checklists/community_governance/maintainers_team.mdx
> +5. [ ] Move members who step down to alumni status on the website in the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```suggestion
5. [ ] Move members who step down to alumni status on the website in the [About > Governance > Maintainers section](https://nf-co.re/governance#maintainers)
```
```suggestion
5. [ ] Move members who step down to alumni status on the website in [**About > Governance > Maintainers**](https://nf-co.re/governance#maintainers)
```

2024-11-14 14:32 UTC, christopher-hakkaart requested changes

2024-11-14 14:51 UTC, christopher-hakkaart approved these changes

2024-11-15 11:37 UTC, merged