Bioconda arm docs
nf-core/website pull request #2899
Opened 2024-12-13 11:31 UTC by ewels

Porting these docs by @dslarm into the nf-core docs:
https://github.com/dslarm/bioconda-contrib-notes/blob/main/README.md

I made a few edits to try to improve readability / make it less personal. But content should be basically the same.

@netlify /docs/contributing/software_packaging/arm64_builds

2024-12-13 11:35 UTC, ewels commented
Deployment preview is borked 😱 

Oldschool preview: [Docs_ arm64 on Bioconda.pdf](https://github.com/user-attachments/files/18125746/Docs_.arm64.on.Bioconda.pdf)

2025-01-14 09:59 UTC, christopher-hakkaart requested changes

2025-01-14 10:00 UTC, christopher-hakkaart approved these changes
Please check comments but nothing that is blocking.

2025-01-14 10:17 UTC, mashehu commented
@nf-core-bot fix linting

2025-01-14 11:58 UTC, dslarm commented on sites/docs/src/content/docs/contributing/software_packaging/arm64_builds.md
> +git push --set-upstream origin ...
=> git push --set-upstream origin aarch64-fixes

2025-01-14 12:05 UTC, ewels commented on sites/docs/src/content/docs/contributing/software_packaging/arm64_builds.md
> +git push --set-upstream origin ...
```suggestion
git push --set-upstream origin aarch64-fixes
```

2025-01-14 13:30 UTC, merged